repository:
  server: github.com
  owner: astrokube
  name: temporal

owners:
  - alias: astrokube-approvers
    members:
      - ivancorrales
      - pasqualet
    roles: ["approver", "reviewer"]
  - alias: astrokube-reviewers
    members:
      - 92nqb
      - redvelvet
    roles: ["reviewer"]

